[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_0_29_support_test = "7AJbUMU8e9i3DocCpCfvGFu3X12SAx5nPnAynd1nFaHD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ""
