[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pyth_lazer_solana_contract = "pytd2yyk641x7ak7mkaasSJVXh6YYZnC7wTmtgAyxPt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout=1000000"
