#!/bin/sh

set -e

if [ "$CI" = "true" ] || [ "$CI" = "1" ]; then
  biome ci --changed --no-errors-on-unmatched --max-diagnostics=none "$@"
else
  biome check --staged --no-errors-on-unmatched --max-diagnostics=none "$@"
  biome check --changed --no-errors-on-unmatched --max-diagnostics=none "$@"
fi
