name: Web CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
    paths:
      - "**.md?"
      - "**.mjs"
      - "**.mts"
      - "**.cjs"
      - "**.cts"
      - "**.tsx?"
      - "**.jsx?"
      - "**.json"
      - "**.sol"
      - "**.html"
      - "**.css"
      - "**.scss"
      - "**.sass"
      - "**.svg"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.gif"
      - "**.webp"
      - "**.avif"
      - "**.ico"
      - "**.woff"
      - "**.woff2"
      - "**.ttf"
      - "**.otf"
      - "**.eot"
      - "**/package.json"
      - "**/bunfig.toml"
      - "**/bun.lock"
      - "**/turbo.json"
      - "**/biome.json"
      - "**/tsconfig.json"
      - .github/workflows/ci-web.yml

permissions:
  contents: read
  pull-requests: write

jobs:
  ci-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: git fetch origin main --depth=1
      - uses: jdx/mise-action@v2
      # Libusb is a build requirement for the node-hid package and so bun
      # install will fail if this isn't in the build environment and if a
      # precompiled binary isn't found.
      - name: Install libusb
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev libudev-dev
      - name: Install dependencies
        run: mise x -- bun install
      - name: Run Dependency Check
        run: |
          echo "## 👁️ JavaScript Dependency Checker" > dependency-check.txt
          echo "" >> dependency-check.txt

          OUTPUT=$(mise x -- bun run dep:check 2>&1 || true)

          if [ -z "$OUTPUT" ]; then
            echo "All dependencies are up-to-date" >> dependency-check.txt
          else
            echo "\`\`\`" >> dependency-check.txt
            echo "$OUTPUT" >> dependency-check.txt
            echo "\`\`\`" >> dependency-check.txt
          fi
      - name: Post Dependency Check Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: dependency-check
          path: dependency-check.txt
      - name: Post CI Check In Progress
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "## ⏳ JavaScript CI checks are currently running... $(date "+%Y-%m-%d %H:%M:%S %Z")" > in-progress-ci.txt
          echo "" >> in-progress-ci.txt
          echo "![Loading](https://media.tenor.com/2BLI5EO7yVAAAAAi/loading-image.gif)" >> in-progress-ci.txt
      - name: Post CI Check In Progress Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-ci
          path: in-progress-ci.txt
      - name: Run CI Checks
        run: |
          set -o pipefail
          mise x -- bun turbo run test:ci 2>&1 | tee ci-output.txt
          mise x -- bun run turbo build 2>&1 | tee -a ci-output.txt
      - name: Post CI Check Success
        if: success()
        run: |
          GIFS=(
          "https://media1.tenor.com/m/pmGxFUf3zMsAAAAC/fired-up-whoo.gif"
          "https://media1.tenor.com/m/FcPBHg9HYx4AAAAd/yeah-fired-up.gif"
          "https://media1.tenor.com/m/dBmmJrN4GvEAAAAC/oh-yes.gif"
          "https://media1.tenor.com/m/Y3PteFSEAj8AAAAC/buttsmarnn-patrick-bateman.gif"
          "https://media1.tenor.com/m/xlhV0tC8tMUAAAAd/nodding-yes.gif"
          "https://media1.tenor.com/m/EeDNVMUFU_YAAAAC/ytmx112.gif"
          "https://media1.tenor.com/m/6jdFG1Z9zecAAAAd/wolf-of-wall-street.gif"
          "https://media1.tenor.com/m/MZ1lyjphrv0AAAAC/make-it-rain-bender.gif"
          "https://media1.tenor.com/m/tt8PLobjayAAAAAC/smile-morpheus.gif"
          "https://media1.tenor.com/m/03-xmqploKcAAAAC/futurama-bender.gif"
          "https://media1.tenor.com/m/oHHBapyVgZsAAAAd/smile-terminator.gif"
          )
          RANDOM_GIF=${GIFS[$RANDOM % ${#GIFS[@]}]}

          echo "## ✅ JavaScript CI checks passed $(date "+%Y-%m-%d %H:%M:%S %Z")" > success-ci.txt
          echo "" >> success-ci.txt
          echo "<img src=\"$RANDOM_GIF\" height=\"360\" width=\"auto\" alt=\"Success\" />" >> success-ci.txt
      - name: Post CI Check Success Comment
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-ci
          path: success-ci.txt
      - name: Prepare CI Check Failure
        if: failure()
        run: |
          GIFS=(
          "https://media1.tenor.com/m/vkodxf_ULOUAAAAC/apocalypsenow-horror.gif"
          "https://media1.tenor.com/m/033_FZJILq0AAAAd/tv-drama.gif"
          "https://media1.tenor.com/m/2nPQjxRj9xQAAAAC/midsommar-screaming.gif"
          "https://media1.tenor.com/m/VyO4QP1HpnsAAAAC/oil-fire.gif"
          "https://media1.tenor.com/m/iQsphkc2q_8AAAAC/meltdown.gif"
          "https://media1.tenor.com/m/P4hIHOVgx2UAAAAC/no-stress.gif"
          "https://media1.tenor.com/m/chfOGBC51icAAAAd/face-creepy-face.gif"
          "https://media1.tenor.com/m/-NZBRCV7nicAAAAd/spiderman-crying.gif"
          "https://media1.tenor.com/m/GEdwZ0Q847UAAAAd/interstellar-matthew-mcconaughey.gif"
          "https://media1.tenor.com/m/1ut6ffLeqSYAAAAC/nuclear-mushroom.gif"
          "https://media1.tenor.com/m/s-4kvwARd0cAAAAC/garfield-sad.gif"
          )
          RANDOM_GIF=${GIFS[$RANDOM % ${#GIFS[@]}]}

          echo "## 🚨 JavaScript CI Checks Failed $(date "+%Y-%m-%d %H:%M:%S %Z")" > ci-failure.txt
          echo "" >> ci-failure.txt
          echo "<img src=\"$RANDOM_GIF\" height=\"360\" width=\"auto\" alt=\"Failure\" />" >> ci-failure.txt
          echo "" >> ci-failure.txt
          echo "\`\`\`" >> ci-failure.txt
          cat ci-output.txt >> ci-failure.txt
          echo "\`\`\`" >> ci-failure.txt
      - name: Post CI Check Failure
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-ci
          path: ci-failure.txt
